# Generated by Django 5.0.6 on 2024-05-13 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=123)),
                ('email', models.CharField(max_length=123)),
                ('phone', models.CharField(max_length=123)),
                ('desc', models.TextField()),
                ('date', models.DateField()),
            ],
        ),
    ]
